# -*- coding: utf-8 -*-
"""test.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SYg6zxEttPS8hhho-l9xLOffXtGJmISJ
"""

def add(x,y):
  return x+y

def mul(x,y):
  return x*y